-- Re-seed ingredients catalog. Names match the screenshots (including spellings like Yogourt, Granolat, Dark Chocolat, etc.).
-- Replace 1 below with your `users.id`, or run: SELECT id FROM users;
INSERT INTO ingredients (user_id, name) VALUES
(1, 'Bocconcini'),
(1, 'Boursin cheese'),
(1, 'Brie Cheese'),
(1, 'Butter'),
(1, 'Buttermilk'),
(1, 'Cheddar Cheese'),
(1, 'Cheese'),
(1, 'Condensed Milk'),
(1, 'Cottage cheese'),
(1, 'Cream'),
(1, 'Cream Cheese'),
(1, 'Feta Cheese'),
(1, 'Greek Yogourt'),
(1, 'Milk'),
(1, 'Parmigiano Reggiano Cheese'),
(1, 'Ricotta Cheese'),
(1, 'Sour Cream'),
(1, 'Whipping Cream'),
(1, 'Yogourt'),
(1, 'Brown Rice'),
(1, 'Fries'),
(1, 'Pasta'),
(1, 'Potato'),
(1, 'Spaghetti'),
(1, 'Sweet potatoes'),
(1, 'White Rice'),
(1, 'Baguette'),
(1, 'Ciabatta'),
(1, 'Flour'),
(1, 'Graham Cracker'),
(1, 'Granolat'),
(1, 'Pita Bread'),
(1, 'Pizza Dough'),
(1, 'Puff Pastry'),
(1, 'Tortillas'),
(1, 'Tostitos Chip'),
(1, 'Whole Grain Bread'),
(1, 'Bacon'),
(1, 'Chicken'),
(1, 'Chicken Broth Concentrate'),
(1, 'Cold Cuts'),
(1, 'Egg'),
(1, 'Ground Beef'),
(1, 'Ground Pork'),
(1, 'Ground Turkey'),
(1, 'Herring'),
(1, 'Meatballs'),
(1, 'Pepperoni'),
(1, 'Pork Chops'),
(1, 'Pork Tenderloin'),
(1, 'Salmon'),
(1, 'Shredded Beef'),
(1, 'Shrimp'),
(1, 'Smoked Meat'),
(1, 'Steak'),
(1, 'Striploin Steak'),
(1, 'Tofu'),
(1, 'Tuna'),
(1, 'Turkey'),
(1, 'Turkey Sausage'),
(1, 'Almond'),
(1, 'Cashews'),
(1, 'Cocoa Powder'),
(1, 'Dark Chocolat'),
(1, 'Macadamia'),
(1, 'Peanut'),
(1, 'Pecans'),
(1, 'Pistachios'),
(1, 'Quick Oats'),
(1, 'Walnuts'),
(1, 'Whole Rolled Oats'),
(1, 'Bagel'),
(1, 'Chia seeds'),
(1, 'Flax Seeds'),
(1, 'Hemp seeds'),
(1, 'Pumpkin Seeds'),
(1, 'Quinoa'),
(1, 'Sesame Oil'),
(1, 'Sesame Seed'),
(1, 'Sunflower seeds'),
(1, 'Basil'),
(1, 'Cinnamon'),
(1, 'Dill'),
(1, 'Garlic'),
(1, 'Ginger'),
(1, 'Green Onion'),
(1, 'Miso Paste'),
(1, 'Nutritional Yeast'),
(1, 'Parsley'),
(1, 'Pesto'),
(1, 'Rosemary'),
(1, 'Sage'),
(1, 'Thyme'),
(1, 'Asparagus'),
(1, 'Avocado'),
(1, 'Beets'),
(1, 'Bell Peppers'),
(1, 'Black beans'),
(1, 'Black Lentils'),
(1, 'Black Olive'),
(1, 'Broccoli'),
(1, 'Bruschetta'),
(1, 'Brussels Sprouts'),
(1, 'Cabbage'),
(1, 'Cannellini Bean'),
(1, 'Carrot'),
(1, 'Cauliflower'),
(1, 'Celery'),
(1, 'Cherry Tomatoes'),
(1, 'Chickpeas'),
(1, 'Chili Pepper'),
(1, 'Chives'),
(1, 'Cucumber'),
(1, 'Edamame'),
(1, 'Eggplant'),
(1, 'Green Beans'),
(1, 'Green Peas'),
(1, 'Hummus'),
(1, 'Jalapeno'),
(1, 'Kale Greens'),
(1, 'Kidney Beans'),
(1, 'Lettuce'),
(1, 'Olive'),
(1, 'Onion'),
(1, 'Parsnips'),
(1, 'Pickle'),
(1, 'Radishes'),
(1, 'Red Onion'),
(1, 'Refried Beans'),
(1, 'Shangai Bok Choy'),
(1, 'Shitake Mushrooms'),
(1, 'Snap peas'),
(1, 'Spinach'),
(1, 'Split peas'),
(1, 'Tomato'),
(1, 'Tomato Paste'),
(1, 'Tomato Sauce'),
(1, 'Turnip greens'),
(1, 'Turnips'),
(1, 'White Onion'),
(1, 'Zucchini'),
(1, 'Apple'),
(1, 'Banana'),
(1, 'Blackberries'),
(1, 'Blueberries'),
(1, 'Cherry'),
(1, 'Cranberries'),
(1, 'Grapes'),
(1, 'Lemon'),
(1, 'Lime'),
(1, 'Mangoes'),
(1, 'Nectarine'),
(1, 'Orange'),
(1, 'Orange Juice'),
(1, 'Peache'),
(1, 'Pineapple'),
(1, 'Raspberries'),
(1, 'Rutabaga'),
(1, 'Strawberrie'),
(1, 'Alfredo Sauce'),
(1, 'Apple Cider Vinegar'),
(1, 'Baking Soda'),
(1, 'Banana Pepper'),
(1, 'Beef Broth Concentrate'),
(1, 'Brown Sugar'),
(1, 'Calrose Rice'),
(1, 'Caramel'),
(1, 'Corn'),
(1, 'Corn Starch'),
(1, 'Cumin'),
(1, 'Extra Virgin Olive Oil'),
(1, 'Fettuccine'),
(1, 'Filo Pastry'),
(1, 'Gnocchi'),
(1, 'Ground Basil'),
(1, 'Ground Chili'),
(1, 'Ground Garlic'),
(1, 'Ground Ginger'),
(1, 'Ground Nutmeg'),
(1, 'Ground Onion'),
(1, 'Ground Oregano'),
(1, 'Hard Egg'),
(1, 'Hoisin Sauce'),
(1, 'Honey'),
(1, 'Jam'),
(1, 'Jasmine Rice'),
(1, 'Kefir'),
(1, 'Lemon Zest'),
(1, 'Macaroni'),
(1, 'Maple Syrup'),
(1, 'Marinara Sauce'),
(1, 'Mashmello'),
(1, 'Mayonnaise'),
(1, 'Mozzarella'),
(1, 'Mustard'),
(1, 'Nutella'),
(1, 'Oyster Sauce'),
(1, 'Paprika'),
(1, 'Parmesan Cheese'),
(1, 'Peanut Butter'),
(1, 'Pear'),
(1, 'Peppemint Extract'),
(1, 'Red Wine'),
(1, 'Relish'),
(1, 'Rice Vinegar'),
(1, 'Romano Cheese'),
(1, 'Salsa'),
(1, 'Soy Milk'),
(1, 'Soy Sauce'),
(1, 'Sriracha'),
(1, 'Sugar'),
(1, 'Swiss Cheese'),
(1, 'Tex Mex Cheese'),
(1, 'Thai sauce'),
(1, 'Vanilla'),
(1, 'Vegetable Broth'),
(1, 'Vegetable Broth Concentrate'),
(1, 'White Chocolat'),
(1, 'White Wine Vinegar');
